In [4]:
import numpy as np

In [5]:
data = np.genfromtxt(
    "sales_data.csv",
    delimiter=",",
    skip_header = 1
)

In [15]:
print(data)

[[1.000e+00 5.600e+01 0.000e+00 ... 3.100e+00 1.000e+00 7.000e+00]
 [2.000e+00 4.600e+01 0.000e+00 ... 2.600e+00 0.000e+00 1.000e+01]
 [3.000e+00 3.200e+01 0.000e+00 ... 2.200e+00 0.000e+00 5.000e+00]
 ...
 [1.998e+03 1.900e+01 1.000e+00 ... 3.800e+00 1.000e+00 4.000e+00]
 [1.999e+03 5.600e+01 1.000e+00 ... 3.400e+00 0.000e+00 1.300e+01]
 [2.000e+03 2.300e+01 0.000e+00 ... 3.000e+00 0.000e+00 6.000e+00]]


Q1. Shape of dataset

In [3]:
data.shape

(2000, 10)

Q2. Number of rows

In [4]:
data.shape[0]

2000

Q3. Number of columns

In [5]:
data.shape[1]

10

Q4. Average customer age

In [6]:
np.mean(data[:, 1])

41.3165

Q5. Minimum & maximum age

In [16]:
np.min(data[:, 1]), np.max(data[:, 1])

(18.0, 64.0)

Q6. Total units sold

In [17]:
np.sum(data[:,4])

50054.0

Q7. Average price per unit

In [18]:
np.mean(data[:, 5])

274.4085

Q8. Total revenue (before discount)

In [20]:
revenue = data[:,4] * data[:,5]
np.sum(revenue)

13720135.0

Q9. Discount amount per row

In [21]:
discount = revenue * (data[:,6] / 100)
np.sum(discount)

1326117.6

Q10. Net revenue

In [22]:
net_revenue = revenue - discount
print(net_revenue)

[19775.25 11178.    1398.4  ...  2506.4    678.3  12711.6 ]


Q11. Total net revenue

In [23]:
np.sum(net_revenue)

12394017.399999999

Q12. Average net revenue

In [24]:
average_net_revenue = np.mean(net_revenue)
average_net_revenue

6197.008699999999

Q13. Customers with units sold > 30

customers = sum(data[data[:,4] > 30])
customers // not ok 

Q14. Average rating

In [6]:
avg_rating = np.mean(data[:,7])
avg_rating

3.00125

Q15. Count of returned orders

In [7]:
np.sum(data[:,8] == 1)

1035

Q16. Return rate (%)

In [14]:
return_rate = np.mean(data[:,8]) * 100
round(return_rate, 2)

51.75

Q15. Count of not returned orders

In [9]:
np.sum(data[:,8] == 0)

965

Q17. Average delivery time

In [15]:
np.mean(data[:,9])

7.388

Q18. Fast deliveries (≤ 3 days)

In [17]:
data[data[:,9] <= 3]

array([[1.100e+01, 2.800e+01, 0.000e+00, ..., 2.800e+00, 1.000e+00,
        2.000e+00],
       [1.500e+01, 4.100e+01, 1.000e+00, ..., 4.100e+00, 0.000e+00,
        1.000e+00],
       [1.700e+01, 3.900e+01, 0.000e+00, ..., 1.200e+00, 0.000e+00,
        3.000e+00],
       ...,
       [1.990e+03, 5.500e+01, 0.000e+00, ..., 4.700e+00, 0.000e+00,
        2.000e+00],
       [1.991e+03, 6.200e+01, 0.000e+00, ..., 4.000e+00, 1.000e+00,
        1.000e+00],
       [1.993e+03, 6.400e+01, 1.000e+00, ..., 2.300e+00, 0.000e+00,
        3.000e+00]])

Q19. Revenue from high discount (≥15%)

In [25]:
np.sum(net_revenue[data[:,6] >= 15])

4427842.75

Q20. Average revenue by gender

In [26]:
np.mean(net_revenue[data[:,2] == 0]), np.mean(net_revenue[data[:,2] == 1])

(5907.021196754565, 6478.988658777121)

Q21. Region with highest average revenue

In [27]:
regions = np.unique(data[:,3])
avg_rev = [np.mean(net_revenue[data[:,3] == r]) for r in regions]
regions[np.argmax(avg_rev)]

5.0

Q22. Standard deviation of price

In [28]:
np.std(data[:,5])

129.27392864669193

Q23. Top 5 transactions by net revenue

In [29]:
data[np.argsort(net_revenue)[-5:]]

array([[1.824e+03, 4.100e+01, 1.000e+00, 1.000e+00, 4.800e+01, 4.640e+02,
        0.000e+00, 4.200e+00, 0.000e+00, 7.000e+00],
       [1.981e+03, 4.700e+01, 1.000e+00, 5.000e+00, 4.900e+01, 4.640e+02,
        0.000e+00, 4.600e+00, 0.000e+00, 9.000e+00],
       [1.409e+03, 1.900e+01, 1.000e+00, 3.000e+00, 4.900e+01, 4.910e+02,
        5.000e+00, 3.500e+00, 1.000e+00, 1.000e+01],
       [1.774e+03, 3.300e+01, 0.000e+00, 4.000e+00, 4.800e+01, 4.930e+02,
        0.000e+00, 3.600e+00, 1.000e+00, 1.100e+01],
       [7.810e+02, 4.000e+01, 1.000e+00, 5.000e+00, 4.900e+01, 4.840e+02,
        0.000e+00, 2.400e+00, 0.000e+00, 3.000e+00]])

Q24. Percentage of customers rating ≥ 4

In [30]:
np.mean(data[:,7] >= 4) * 100

26.35

Q25. Add net revenue as a new column

In [31]:
final_data = np.column_stack((data, net_revenue))
final_data.shape

(2000, 11)